name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:16.1-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check server
        run: npm run type-check -w=server

      - name: Lint server
        run: npm run lint -w=server

      - name: Test server
        run: npm run test -w=server

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Start server for E2E tests
        run: npm run start -w=server &
        env:
          DB_USER: user
          DB_PASSWORD: password
          DB_NAME: testdb

          PORT: 3000

      - name: Build front end for E2E tests
        run: npm run build -w=client
        env:
          VITE_API_ORIGIN: http://localhost:3000
          VITE_API_PATH: /api/v1/trpc

      - name: Wait for server to startup
        uses: Jtalk/url-health-check-action@v3.2
        with:
          max-attempts: 5
          retry-delay: 5s
          url: http://localhost:3000/api/health

      - name: Test client E2E
        run: npm run test:e2e -w=client

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 7
